export type PhotoCategory = 'Casamentos' | 'Jardim' | 'Salão' | 'Ambientes'

export type Photo = {
  src: string
  alt: string
  width: number
  height: number
  category: PhotoCategory
  caption: string
  /** Prévia borrada (16 px, base64) exibida na hora enquanto a foto carrega */
  blurDataURL?: string
}

const p = (
  file: string,
  width: number,
  height: number,
  category: PhotoCategory,
  caption: string,
  alt: string,
  blurDataURL?: string,
): Photo => ({ src: `/images/fotos/${file}.webp`, width, height, category, caption, alt, blurDataURL })

/** Props do next/image para mostrar a prévia borrada: `<Image {...blur(foto)} ... />` */
export const blur = (photo: Photo) =>
  photo.blurDataURL ? { placeholder: 'blur' as const, blurDataURL: photo.blurDataURL } : {}

/**
 * Fotos reais do Lanai: perfil público no Casamentos.com.br e site antigo (Wayback Machine).
 * Tratadas em WebP, até 2400 px: Real-ESRGAN no original limpo, misturado ao original (Lanczos), sem cara de "cera".
 * A marca do Casamentos.com.br (centro) foi retocada; nos pubs, a faixa com a assinatura do fotógrafo foi recortada.
 * Gerado a partir de statics/image/photos-map.json.
 */
export const photos = {
  // ---- cerimônia e jardim ----
  corredorLuzes: p(
    'cerimonia-corredor-de-luzes-noite',
    2400,
    1600,
    'Jardim',
    'Túnel de luzes',
    'Corredor de cerimônia sob as árvores iluminado por cordões de luz à noite, com cadeiras e flores brancas',
    'data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAsAAsBMJQBOgMXh4T/HadSGwAD+9vIsOSz1n9/j/Sm/D1m5MgLyXRJze0RD2Em+GHQ6mz2zzjtS7SwLdBNeoq5v2aJa9dCtm6ZFOMsRiigHyqAAAA==',
  ),
  cerimoniaJabuticabeiras: p(
    'cerimonia-sob-as-jabuticabeiras',
    2400,
    1600,
    'Jardim',
    'Cerimônia sob as jabuticabeiras',
    'Altar montado sob a alameda de jabuticabeiras, com flores brancas e cadeiras de madeira',
    'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAsAAsBMJYgCdAYvrGOdI06AAP7pHvUxZFySOp+ubIoOVe1pqPv7GtxwFEepUNhdprGMpICRBu7x/Pb6WZ2Ggu3bX1RL9c31u7sSKdLS/1VT0M37UUcFAAA=',
  ),
  altarFlores: p(
    'altar-flores-jardim',
    2400,
    1600,
    'Jardim',
    'Altar no jardim',
    'Altar com cortinas brancas e arranjos de flores entre as árvores do jardim',
    'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAsAAsBMJbACdAENga9F0KbaAP75LTTw8a6mcZK2/Veyz1njC+Oufq1SzWDf/qitM5p8V8o4JOWwiE7HRzhOw6KINw3El/U8QCEcE6epXPuSX7Hb5+cAwVa0AAAA',
  ),
  corredorFlores: p(
    'corredor-flores-luminarias',
    1600,
    2400,
    'Jardim',
    'Corredor de flores',
    'Corredor da cerimônia com flores brancas e luminárias entre as árvores',
    'data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoLABAAAsBMJQBOgCHTA+B+YAD++Ruerx+mpoUsyF8bnPmVS05pTRe/IClv0Hobk9gWQOt0YeL9vh0WLEUPSeHeuToOVNIVQ9AG0AAA',
  ),
  passarelaJardim: p(
    'passarela-do-jardim',
    1598,
    2400,
    'Jardim',
    'Passarela',
    'Passarela clara entre as árvores, decorada com flores amarelas',
    'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoLABAAAsBMJbACdADdSVJ2gagAAP70ttGQefxy1yP49rbZDoC2chOqHD7XXArh2Yv8jLNxboo7hsHO0Tz0eUl/uENSvNsQpJ75GFLePwYOOxDq6Ma+2gMgxNwlVSRRLgAAAA==',
  ),
  jardimMesas: p(
    'jardim-mesas-sob-as-arvores',
    2400,
    1598,
    'Jardim',
    'Recepção no jardim',
    'Mesas da recepção montadas à sombra das árvores, sobre caminho de pedras',
    'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAsAAsBMJQBOgCLO7UtfsPCQAAD+8OgZxUwZNullmZb7PQdezh6lKD9ibAwdoCFKyQtM1XV6csag9rqIL0F13XYT9HSDLLIiuMJpJzKKJ+AA',
  ),
  pergolado: p(
    'pergolado-area-externa',
    2400,
    1601,
    'Jardim',
    'Pergolado',
    'Pergolado de madeira e tijolos com mesas montadas, cercado de plantas',
    'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAQCdASoQAAsAAsBMJZgCdADN+oAikAD+wHtU597GPQ72AfHp3YWp3dFMYD+4AU8qp7tQFnIAbGSg3EGhsrHS5LZx3AkhIQKWapap63EInanV370nAazhdLaNVMwmpJuqgAAA',
  ),
  pergoladoMesa: p(
    'pergolado-mesa-posta',
    1600,
    2400,
    'Jardim',
    'Sob o pergolado',
    'Mesa posta sob o pergolado iluminado, com flores e velas',
    'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQAgCdASoLABAAAsBMJZACdAYv/kr3atpTLAAA/iT9OR6RuO5SmDDpaQ6jAVHkHIeQQGTcptsxB4gT34mGhU6eQ6Qj2m9V8MVQEhKCCTe6V5VpTj9Z5zdlh0Pd92TfjrAyyeI/LEXoFrLE38AAAA==',
  ),
  caminhoJardim: p(
    'caminho-de-pedras-jardim',
    2400,
    1599,
    'Jardim',
    'Caminho do jardim',
    'Caminho de pedras no jardim decorado com flores coloridas e lanternas',
    'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQAgCdASoQAAsAAsBMJZgCdAYsP2WNkIP2/gAA/qxIAF04iolacWE7b65EW3JIXWz5GGrFEpuisLDMnRc0Lwat5YwvgpTwvJ5wOhr/yNEfp9WKGTPlU1GtLYtpMYZE4Tmf5WN8AAA=',
  ),
  gazeboNoite: p(
    'gazebo-noite',
    2400,
    1391,
    'Jardim',
    'O gazebo à noite',
    'Gazebo de madeira e tijolos iluminado à noite, com caminho de pedras',
    'data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAQCdASoQAAkAAsBMJYwCdAEO+Wd8oAD++l5Hf7IkuLe1IQuwRPlzoAA=',
  ),
  pergoladoDoces: p(
    'pergolado-mesa-de-doces',
    2400,
    1391,
    'Jardim',
    'Mesa de doces',
    'Mesa de doces sob o pergolado iluminado à noite',
    'data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAkAAsBMJaACdAD2PVpK0gAA/vr4seVrqPvb9Ab3mh7JvyBXULVWHQdZXU8FKcvHa8M/63KsX/CFjmFqWYtP05vGOQDoXWauKhtAsh5prhNVEAA=',
  ),
  jardimIluminado: p(
    'jardim-iluminado-noite',
    2400,
    1601,
    'Jardim',
    'Jardim iluminado',
    'Árvores do jardim iluminadas em verde à noite',
    'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAsAAsBMJbACdAYvXvz/aAb2kAD+9eFEh71Ejk84FM7e+wOkXNXAjGPkVUAvFRvv+WzzVAqyQs8J/Pnf3WWvzW8rTsG5amlG0k20l78nhu+z5SKififcAAA=',
  ),
  // ---- salão ----
  salaoLustre: p(
    'salao-lustre-de-cristal',
    2400,
    1600,
    'Salão',
    'O salão',
    'Salão com telhado colonial, lustre de cristal, mesas redondas e janelas para o jardim',
    'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAsAAsBMJZgCdAEXZ2MJgaf/gAD+9pRBP0jsj2gRL7w6a3+slaV+6T7FpUP0EEDKxZZ4ijjyzp6BB0L58VAc4404i1rW75UrJ64Wy3xHTu9o7BZBYEGKb2QAAA==',
  ),
  salaoDia: p(
    'salao-montado-de-dia',
    2400,
    1600,
    'Salão',
    'Salão de dia',
    'Salão montado durante o dia, com lustre, mesas e grandes janelas para o verde',
    'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAsAAsBMJaACdACvo3VCYAD++FmrbsdzVtePuW7ASQjQItAgyGMI+DZyqUe2Y+waTOH24e736V4QUvSfwJVawLUlDxJ3yhqUCfcS22gAAA==',
  ),
  salaoMesas: p(
    'salao-mesas-de-madeira',
    2400,
    1600,
    'Salão',
    'Mesas postas',
    'Mesas de madeira postas no salão, com flores brancas e cadeiras douradas',
    'data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABwAgCdASoQAAsAAsBMJZACdAYubn1D3tEyfoQAAP7HLFZ0pyrKj25FPWritdi0NJN/i96J9qsRYXeiIsU/fbfrW9QVAXC2YxwOWNfllmXtkUoxaPZxt1Rm4wcuyLoA4ntX+PqjXb4Z2OpxiAA=',
  ),
  salaoNoite: p(
    'salao-festa-noite',
    2400,
    1599,
    'Salão',
    'A festa',
    'Salão à noite com mesas decoradas, iluminação azul e lustres para a festa',
    'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwAgCdASoQAAsAAsBMJZACdAYu5VtHnzVQAAD+9v0gEEVfR6mgY/2+RP/Z6lpI2n/zI4tkF6efToUedZkxxA2Ci7LIJswiMAPdhZmr/mmO4AeTxQCPWjGviMy7pYcUvsAlIeUBlE8nl8uq+gAAAA==',
  ),
  // ---- momentos dos casais ----
  saidaNoivos: p(
    'saida-dos-noivos',
    2400,
    1600,
    'Casamentos',
    'A saída dos noivos',
    'Noivos saindo da cerimônia sob as árvores, aplaudidos pelos convidados',
    'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQAgCdASoQAAsAAsBMJZACdAYvDjDBHUVOWgAA/veb9Yk8ANB2draKDOHGdhPT057u3ydVsM5k8v3WmoDrwLmUfyiP+07y2/ufxYHF45pqlY+Q9yQNEOAW9x9DoxbVkd7TmqPZNhSc518dbIaAAA==',
  ),
  noivosAltar: p(
    'noivos-altar-por-do-sol',
    1600,
    2400,
    'Casamentos',
    'O beijo no altar',
    'Noivos se beijando no altar florido entre as árvores, ao pôr do sol',
    'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABwAgCdASoLABAAAsBMJaACdAYula3c7kwjegAAAP7weyE5pMuHV9sMQ7CUbqm8IsSRqmzdrPVvNE7uBuMaErlLI0K/B0aRUduurNX07yDlwidDFSOpxpX4L7j9LsWQaXVdbZPy7Iq2o3PYKCWAAA==',
  ),
  cerimoniaPorDoSol: p(
    'cerimonia-arvores-por-do-sol',
    1600,
    2400,
    'Casamentos',
    'Cerimônia ao pôr do sol',
    'Cerimônia ao ar livre sob as árvores, com a luz dourada do fim de tarde',
    'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwAgCdASoLABAAAsBMJQBOgMWgtpH73IT1AAD+9yl82WdZM//eLDIhAhd8EBLU2yfMgTPl1nBaE2I3ST1mytLxXt+KijHhIJs+kUXYSsrS/J7Ldq3kMGisldPJZWZJV4LeGQevslcAagAA',
  ),
  suiteVestido: p(
    'suite-da-noiva-vestido',
    1597,
    2400,
    'Casamentos',
    'A noiva',
    'Noiva de vestido na suíte, ao lado de uma daminha',
    'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABwAgCdASoLABAAAsBMJYgCdAYvrzYkgeut2OAAAP6YQrV9XRuq7BUVfxPtQVSQaRN0WcZBD4uf0pg24Blf9YYGwwOj2ktkYVafOuuDM1hXkX8K/4cUiekVGJnuTbpqUr+6AzseEdqVer2IZwAAAA==',
  ),
  noivaMakingOf: p(
    'noiva-making-of',
    2400,
    1600,
    'Casamentos',
    'Preparação',
    'Noiva sorrindo durante a preparação, segurando uma caixa de presente',
    'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQAgCdASoQAAsAAsBMJZACdAYuldhB7IwAAPjUSQbUpOse8ygFPdHFK1CBa9dV7Qez+Y2BVGM76o2b9CXoZZsyXJND4NCJ7cWWCh85ZoyXAHdayve295z5XUoPkOqeLhkc856ujzVGJm/VkTwAAA==',
  ),
  pistaPrimeiraDanca: p(
    'pista-primeira-danca',
    1600,
    2400,
    'Casamentos',
    'A primeira dança',
    'Noivos dançando na pista do salão, cercados pelos convidados',
    'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoLABAAAsBMJQBOj+ADM51Q/uqp0AD++mkFw8tJjGu7bUxwncmNaE7ceJZNpR/Ls8/LT679tvAYBAhI4b+XpRjSgxOCaNGNHyPH8Aw4AAA=',
  ),
  pistaNoiva: p(
    'pista-noiva',
    1600,
    2400,
    'Casamentos',
    'A noiva na pista',
    'Noiva comemorando na pista com os convidados',
    'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoLABAAAsBMJQBYebQAPwkWd33UAP768g6HgqeHMcveSKUDOYrZqFCN5lyaunApcDVxTeUgU6qxoKRHE20c/Qe0FM7MTuaenNR7DHVym/xXiux3C3NVyn+yjaGoNgAA',
  ),
  pistaShow: p(
    'pista-show',
    1600,
    2400,
    'Salão',
    'Show na pista',
    'Show com luzes coloridas na pista do salão',
    'data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoLABAAAsBMJZQCsAEPAtwHHMtAAP77a4dulde/wsKKOMHqigkTJRg+oOSamU63nGNfnV8PeSaI+mnJ4tNtCtPMYdWJwIjmK49LLAAA',
  ),
  valsa: p(
    'valsa-dos-noivos',
    1600,
    2400,
    'Casamentos',
    'A valsa',
    'Noivos dançando a valsa no salão, sob os lustres',
    'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoLABAAAsBMJZQAAu05R5g2pAAA/veqL8hIu2FeY92sYNeE8KY3jSJNoYQ4OxvF7j7E2A0oLQYK0vAQDgoKFFDpLhTVBF3D48WVmrUt255P3DLNkCtgAC8OjwAAAA==',
  ),
  // ---- ambientes de apoio ----
  suiteMadrinhas: p(
    'suite-da-noiva-madrinhas',
    2400,
    1600,
    'Ambientes',
    'Suíte da noiva',
    'Noiva e madrinhas brindando na suíte da noiva, com o letreiro neon Lanai',
    'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAsAAsBMJbACdLoAArBAu22DAAD40Z2MMfTOvTEZQdEyIeKYxin4Doy78PU9RO5odkx9fZZYuQqPEXyXb7a4lTIv/FufpJJfh/qvEFJ1wAAA',
  ),
  suitePreparacao: p(
    'suite-da-noiva-preparacao',
    1600,
    2400,
    'Ambientes',
    'Making of',
    'Noiva sendo maquiada na suíte da noiva, com o letreiro Lanai ao fundo',
    'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoLABAAAsBMJZACdAD5fojRaMAA+unmJByHEk3GM7VztbdNKcsn33HkAXvk3lXNRIBX33KPUtChf752q60/F0kkPXTn5NjTJHpESIH3zSgjVLe31SBh6qsy7yAAAA==',
  ),
  pubSinuca: p(
    'pub-do-noivo-sinuca',
    2400,
    1444,
    'Ambientes',
    'Pub do noivo',
    'Pub do noivo com mesa de sinuca, banquetas e piso geométrico',
    'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAoAAsBMJQBOgCKV8648wLAA/vauJ+fJJrF6WLShXR9yc85smOuP0/6ONjCfhq75QqTAr6ETuRA4RHNezSuoP62OP59AjEyHRTZDwdeqqAAA',
  ),
  pubLounge: p(
    'pub-do-noivo-lounge',
    2400,
    1444,
    'Ambientes',
    'Lounge do pub',
    'Lounge do pub do noivo com sofá de couro e letreiro Lanai iluminado',
    'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAoAAsBMJbACdADCtx5WgJAA/vrv4dKPS4E8y6OZ5Vwlm/fyUfod6aFEdSpO0WYjbAcvHTJKcja8CYs5kX4bq4wSi0foRua8pIEn5wAAAA==',
  ),
  pubMesa: p(
    'pub-do-noivo-mesa',
    2400,
    1444,
    'Ambientes',
    'Pub: sinuca',
    'Mesa de sinuca do pub do noivo com o logo Lanai',
    'data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAoAAsBMJZACdAEPDOzpTca4AP752PeXgVNOi7zC12lIUB4e1unba+ef0cBWSdafyjLNMNJgh2v2/tyPfGDZejKbtEWNcNdBTLIgw3Qk9fKRHQAAAA==',
  ),
  pubAdega: p(
    'pub-do-noivo-adega',
    2400,
    1444,
    'Ambientes',
    'Pub: adega',
    'Adega climatizada e quadros no pub do noivo',
    'data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAoAAsBMJZgCdADHj1eY0gAA/eOXayz3fx8+GxkYf22UwNveenp+xJ5VmmV7NX8RjrH2F3UHtgTwfvb+DhdiPUVffGW2hOW3MpYvIthSeYwnCUAAAA==',
  ),
  brinquedoteca1: p(
    'brinquedoteca-1',
    2400,
    1800,
    'Ambientes',
    'Brinquedoteca',
    'Brinquedoteca colorida com mesinha, estante de brinquedos e televisão',
    'data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAQCdASoQAAwAAsBMJbACdADGZaiLjQAA/uW+90hskx989a7iYMLa09Ophpt6dStsl0q5yphsGOJ5/i2MYZrEjla6I+yyNqPpDUntbpXF7YC+Q2Mi8bMW//Vh5ngijop5tpTSbhWxjLQAAAA=',
  ),
  brinquedoteca2: p(
    'brinquedoteca-2',
    2400,
    1800,
    'Ambientes',
    'Espaço kids',
    'Espaço kids com cadeirinhas coloridas e túnel de brincar',
    'data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAQCdASoQAAwAAsBMJbACdACRXpJ6uAAA/VN0elVpXPBav3Q+/Ifq6nGDcWkV0Kj9nexKsVXiO36sV7ARLKpykqhu6HAt8+qs/HpiHx7XDpBJYG3ascpAev8XJyMXI66xDvag2ei0LsgAAAA=',
  ),
  brinquedoteca3: p(
    'brinquedoteca-3',
    2400,
    1800,
    'Ambientes',
    'Brinquedoteca: berço',
    'Brinquedoteca com berço, mesinha e painel ilustrado',
    'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwAgCdASoQAAwAAsBMJbACdAD2Pvfo5Yo0gADOOLJV9h3Qnn/TNyUtOsqJU0ANTRvHtcpsSEk4gI8GP8m/aDvI4HU3RPK+HZBbZz2PrMZnXfh3DvlDU+BEDzk7uZ3QyK0CnQbLMfckAAAA',
  ),
  brinquedoteca4: p(
    'brinquedoteca-4',
    1801,
    2400,
    'Ambientes',
    'Brinquedos',
    'Cantinho de brinquedos com estante e cadeirinhas',
    'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoMABAAAsBMJbACdAEfA5+6Ww8JaQAA9rFrKDGSJ5kVsIiU9+4q4Qin+VpDlV+4RkzfVmx3ugfgyVxWJRwhVAEiKxhBWGE/DTH5hF/VxH5WjvdFr8s5+tPOj0ZoAA==',
  ),
} satisfies Record<string, Photo>

/** Fotos do topo da home (carrossel). */
export const heroSlides: Photo[] = [
  photos.corredorLuzes,
  photos.cerimoniaJabuticabeiras,
  photos.salaoLustre,
  photos.jardimMesas,
]

/** Faixa de momentos (fotos verticais). */
export const momentsPhotos: Photo[] = [
  photos.noivosAltar,
  photos.suiteVestido,
  photos.corredorFlores,
  photos.pistaPrimeiraDanca,
  photos.cerimoniaPorDoSol,
  photos.valsa,
  photos.passarelaJardim,
  photos.pistaNoiva,
  photos.pergoladoMesa,
  photos.pistaShow,
]

/** Galeria completa (ordem pensada para alternar ambientes e momentos). */
export const galleryPhotos: Photo[] = [
  photos.corredorLuzes,
  photos.salaoLustre,
  photos.noivosAltar,
  photos.cerimoniaJabuticabeiras,
  photos.saidaNoivos,
  photos.jardimMesas,
  photos.suiteVestido,
  photos.salaoDia,
  photos.altarFlores,
  photos.pistaPrimeiraDanca,
  photos.pergolado,
  photos.suiteMadrinhas,
  photos.corredorFlores,
  photos.salaoNoite,
  photos.gazeboNoite,
  photos.valsa,
  photos.caminhoJardim,
  photos.salaoMesas,
  photos.cerimoniaPorDoSol,
  photos.pubLounge,
  photos.pergoladoMesa,
  photos.noivaMakingOf,
  photos.passarelaJardim,
  photos.pistaShow,
  photos.pergoladoDoces,
  photos.suitePreparacao,
  photos.pubSinuca,
  photos.pistaNoiva,
  photos.jardimIluminado,
  photos.pubMesa,
  photos.brinquedoteca1,
  photos.pubAdega,
  photos.brinquedoteca2,
  photos.brinquedoteca3,
  photos.brinquedoteca4,
]
